[project]
name = "renovate-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "private-torarvid-package-1>=0.0.2",
]
